version: '3.4'

services:

    portainer:
        image: portainer/portainer-ce
        container_name: portainer       
        restart: always
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - observability-network

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8086:8086            
        volumes:
            - influxdb-data:/var/lib/influxdb
        networks:
            - observability-network

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana-data:/var/lib/grafana            
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        networks:
            - observability-network

networks:
    observability-network:
        driver: bridge

volumes:
    influxdb-data:
        driver: local
    grafana-data:
        driver: local
    portainer_data:
        driver: local